#name: 'user-srv'
#
#mysql:
#  host: '127.0.0.1'
#  port: 3307
#  user: 'root'
#  password: '1234'
#  db: 'mxshop_goods_srv'
#
#consul:
#  host: '127.0.0.1'
#  port: 8501


host: '127.0.0.1'
port: 8850
namespace: 'a81371ea-a7c9-44c2-bba3-a8e74eca3f7f'
user: 'nacos'
password: 'nacos'
dataid: 'goods-srv.json'
group: 'dev'